version: '2'
services:
    frontend:
        # build: /home/mahdi/IENOW/JobOonja-Client/.
        build: ../../IENOW/JobOonja-Client/
        ports: 
            - "3000:5000"
        depends_on:
            - backend      
    backend:
        build: .
        ports: 
            - "8080:8080"
        depends_on:
            - db
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: IE
            # MYSQL_USER: root
            # MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        volumes:
            - my-datavolume:/var/lib/mysql
volumes:
     my-datavolume:

